version: "3.9"
services:

  hub:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"

    environment:
      GRID_MAX_SESSION: 16
      GRID_BROWSER_TIMEOUT: 3000
      GRID_TIMEOUT: 3000

  chrome:
    image: selenium/node-chrome-debug
    container_name: web-chrome1
    depends_on:
      - hub
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
      NODE_MAX_SESSION: 8
      NODE_MAX_INSTANCES: 8
    ports:
      - "5900:5900"
    links:
      - hub